name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 'latest'
      - name: Install dependencies
        run: pnpm install
      - name: Run Update Browserslist
        run: npx update-browserslist-db@latest
      - name: Build website
        run: pnpm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
